// <auto-generated />
using System;
using API_Envios.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Envios.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260526154923_AddHistorialUsuarioRelationship")]
    partial class AddHistorialUsuarioRelationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_Envios.Models.Destinatario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId");

                    b.ToTable("Destinatarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Departamento = "San Salvador",
                            Direccion = "San Salvador",
                            Distrito = "San Salvador Centro",
                            EmpresaId = 1,
                            Nombre = "Michelle Jimenez",
                            Telefono = "77777777"
                        });
                });

            modelBuilder.Entity("API_Envios.Models.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activa")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Empresas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activa = true,
                            Correo = "empresa@envios.test",
                            Departamento = "San Salvador",
                            Direccion = "Colonia Escalon",
                            Distrito = "San Salvador Centro",
                            Nit = "0614-260526-101-1",
                            Nombre = "Mishi Store",
                            Telefono = "77777777"
                        });
                });

            modelBuilder.Entity("API_Envios.Models.Envio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoRastreo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("DescripcionPedido")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DestinatarioId")
                        .HasColumnType("int");

                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaEntrega")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirmaRecibido")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("ImagenesEntrega")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PesoLibras")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int?>("PilotoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodigoRastreo")
                        .IsUnique();

                    b.HasIndex("DestinatarioId");

                    b.HasIndex("EmpresaId");

                    b.HasIndex("PilotoId");

                    b.ToTable("Envios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoRastreo = "ENV-20260526-0001",
                            DescripcionPedido = "Paquete de prueba",
                            DestinatarioId = 1,
                            EmpresaId = 1,
                            Estado = "EnRuta",
                            FechaCreacion = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            ImagenesEntrega = "[]",
                            PesoLibras = 2.5m,
                            PilotoId = 1
                        });
                });

            modelBuilder.Entity("API_Envios.Models.HistorialEnvio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EnvioId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EnvioId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("HistorialEnvios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comentario = "Envio creado",
                            EnvioId = 1,
                            Estado = "Recolectado",
                            Fecha = new DateTime(2026, 5, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Usuario = "Sistema",
                            UsuarioId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comentario = "Asignado a piloto demo",
                            EnvioId = 1,
                            Estado = "EnRuta",
                            Fecha = new DateTime(2026, 5, 26, 0, 5, 0, 0, DateTimeKind.Utc),
                            Usuario = "Administrador Master",
                            UsuarioId = 1
                        });
                });

            modelBuilder.Entity("API_Envios.Models.Piloto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Pilotos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Departamento = "San Salvador",
                            Distrito = "San Salvador Centro",
                            Documento = "00000000-0",
                            Nombre = "Piloto Demo",
                            Telefono = "77770000"
                        });
                });

            modelBuilder.Entity("API_Envios.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Departamento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DireccionCercana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distrito")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PilotoId")
                        .HasColumnType("int");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("Id");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.HasIndex("PilotoId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Correo = "master@envios.test",
                            Nombre = "Administrador Master",
                            Password = "Master123",
                            Rol = "AdministradorMaster"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Correo = "admin@envios.test",
                            Departamento = "San Salvador",
                            DireccionCercana = "Centro",
                            Distrito = "San Salvador Centro",
                            Nombre = "Admin San Salvador",
                            Password = "Admin123",
                            Rol = "Administrador"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Correo = "empresa@envios.test",
                            EmpresaId = 1,
                            Nombre = "Mishi Store",
                            Password = "Empresa123",
                            Rol = "EmpresaCliente"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Correo = "piloto@envios.test",
                            Nombre = "Piloto Demo",
                            Password = "Piloto123",
                            PilotoId = 1,
                            Rol = "Piloto"
                        });
                });

            modelBuilder.Entity("API_Envios.Models.Destinatario", b =>
                {
                    b.HasOne("API_Envios.Models.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("API_Envios.Models.Envio", b =>
                {
                    b.HasOne("API_Envios.Models.Destinatario", null)
                        .WithMany()
                        .HasForeignKey("DestinatarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_Envios.Models.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("API_Envios.Models.Piloto", null)
                        .WithMany()
                        .HasForeignKey("PilotoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("API_Envios.Models.HistorialEnvio", b =>
                {
                    b.HasOne("API_Envios.Models.Envio", null)
                        .WithMany("Historial")
                        .HasForeignKey("EnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_Envios.Models.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("API_Envios.Models.Usuario", b =>
                {
                    b.HasOne("API_Envios.Models.Empresa", null)
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("API_Envios.Models.Piloto", null)
                        .WithMany()
                        .HasForeignKey("PilotoId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("API_Envios.Models.Envio", b =>
                {
                    b.Navigation("Historial");
                });
#pragma warning restore 612, 618
        }
    }
}
