// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using appweb2.Data;

#nullable disable

namespace appweb2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422015721_inicia")]
    partial class inicia
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("appweb2.Models.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Categorias", null, t =>
                        {
                            t.HasCheckConstraint("CK_Categorias_Nombre_NoVacio", "LEN(LTRIM(RTRIM([Nombre]))) > 0");
                        });
                });

            modelBuilder.Entity("appweb2.Models.Compra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCompra")
                        .HasColumnType("datetime2");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int");

                    b.Property<int>("VideoJuegoID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioID");

                    b.HasIndex("VideoJuegoID");

                    b.ToTable("Compras", (string)null);
                });

            modelBuilder.Entity("appweb2.Models.DetalleCompra", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("VideoJuegosId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("cantidad")
                        .HasColumnType("int");

                    b.Property<string>("codigoTransaccion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("estadoCompra")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("fechaHoraTransaccion")
                        .HasColumnType("datetime2");

                    b.Property<int>("idCompra")
                        .HasColumnType("int");

                    b.Property<decimal>("total")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("id");

                    b.HasIndex("idCompra");

                    b.ToTable("detalle_compra", null, t =>
                        {
                            t.HasCheckConstraint("CK_DetalleCompra_Cantidad_Positiva", "[cantidad] > 0");

                            t.HasCheckConstraint("CK_DetalleCompra_Total_NoNegativo", "[total] >= 0");
                        });
                });

            modelBuilder.Entity("appweb2.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("appweb2.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(153)
                        .HasColumnType("nvarchar(153)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(103)
                        .HasColumnType("nvarchar(103)");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("appweb2.Models.VideoJuego", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EdadMinima")
                        .HasColumnType("int");

                    b.Property<bool>("EnPromocion")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Imagen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("PrecioPromocion")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("VideoJuegos", null, t =>
                        {
                            t.HasCheckConstraint("CK_VideoJuegos_EdadMinima_Valida", "[EdadMinima] BETWEEN 0 AND 21");

                            t.HasCheckConstraint("CK_VideoJuegos_PrecioPromocion_Valido", "[PrecioPromocion] IS NULL OR ([PrecioPromocion] > 0 AND [PrecioPromocion] < [Precio])");

                            t.HasCheckConstraint("CK_VideoJuegos_Precio_MayorACero", "[Precio] > 0");
                        });
                });

            modelBuilder.Entity("appweb2.Models.Compra", b =>
                {
                    b.HasOne("appweb2.Models.Usuario", "Usuario")
                        .WithMany("compras")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("appweb2.Models.VideoJuego", "VideoJuego")
                        .WithMany()
                        .HasForeignKey("VideoJuegoID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");

                    b.Navigation("VideoJuego");
                });

            modelBuilder.Entity("appweb2.Models.DetalleCompra", b =>
                {
                    b.HasOne("appweb2.Models.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("idCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Compra");
                });

            modelBuilder.Entity("appweb2.Models.Usuario", b =>
                {
                    b.HasOne("appweb2.Models.Role", "Role")
                        .WithMany("Usuarios")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("appweb2.Models.VideoJuego", b =>
                {
                    b.HasOne("appweb2.Models.Categoria", "Categoria")
                        .WithMany("VideoJuegos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("appweb2.Models.Categoria", b =>
                {
                    b.Navigation("VideoJuegos");
                });

            modelBuilder.Entity("appweb2.Models.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("appweb2.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("appweb2.Models.Usuario", b =>
                {
                    b.Navigation("compras");
                });
#pragma warning restore 612, 618
        }
    }
}
